# Generated by Django 2.1.7 on 2019-06-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('datePlayed', models.DateField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(verbose_name='Round 1 Score')),
                ('score2', models.IntegerField(verbose_name='Round 2 Score')),
                ('score3', models.IntegerField(verbose_name='Round 3 Score')),
                ('score4', models.IntegerField(verbose_name='Round 4 Score')),
                ('score5', models.IntegerField(verbose_name='Round 5 Score')),
                ('score6', models.IntegerField(verbose_name='Round 6 Score')),
                ('score7', models.IntegerField(verbose_name='Round 7 Score')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cgs.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cgs.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='scores',
            name='game',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='player',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
